# compose.override.yml
services:
  api:
    depends_on: []
    volumes:
      - /mnt/8TB_2025:/data:ro
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - NEO4J_URI=bolt://host.docker.internal:7687

  worker:
    depends_on: []
    volumes:
      - /mnt/8TB_2025:/data:ro
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - NEO4J_URI=bolt://host.docker.internal:7687

  # OPTIONAL: disable local infra if you already run them on host
  neo4j:
    profiles: ["infra"]
  ollama:
    profiles: ["infra"]
