
version: "3.9"
services:
  neo4j:
    image: neo4j:5.22
    container_name: assistx-neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-password}
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=1G
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  ollama:
    image: ollama/ollama:latest
    container_name: assistx-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  redis:
    image: redis:7-alpine
    container_name: assistx-redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: assistx-api
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.1:8b}
      - CACHE_PATH=/app/.assistx_cache.sqlite
      - BASIC_AUTH_USER=${BASIC_AUTH_USER:-admin}
      - BASIC_AUTH_PASS=${BASIC_AUTH_PASS:-admin}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - neo4j
      - ollama
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./.assistx_cache.sqlite:/app/.assistx_cache.sqlite
      - ./artifacts:/app/artifacts

  worker:
    build: .
    container_name: assistx-worker
    command: python /app/worker.py
    environment:
      - REDIS_URL=redis://redis:6379/0
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.1:8b}
      - CACHE_PATH=/app/.assistx_cache.sqlite
    depends_on:
      - redis
      - neo4j
      - ollama

volumes:
  neo4j_data: {}
  ollama_data: {}
