services:
  redis:
    image: redis:7-alpine
    container_name: assistx-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assistx-api
    environment:
      # --- AssistX core ---
      - BASIC_AUTH_USER=${BASIC_AUTH_USER:-admin}
      - BASIC_AUTH_PASS=${BASIC_AUTH_PASS:-change-me}
      - API_TOKEN=${API_TOKEN:-}                    # if set, /upload-audio requires x-api-token
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS:-*}

      # --- Datastores (defaults assume containerized infra) ---
      - NEO4J_URI=${NEO4J_URI:-bolt://neo4j:7687}
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-livelongadnprosper}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}

      # --- Ollama (optional) ---
      - OLLAMA_HOST=${OLLAMA_HOST:-http://ollama:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.1:8b}

      # --- Whisper runtime knobs ---
      - WHISPER_DEVICE=${WHISPER_DEVICE:-auto}      # auto|cpu|cuda
      - WHISPER_COMPUTE_TYPE=${WHISPER_COMPUTE_TYPE:-int8}
      - TRANSCRIPTIONS_ROOT=/app/transcriptions
      - XDG_CACHE_HOME=/app/.cache

      # --- App paths ---
      - CACHE_PATH=/app/.assistx_cache.sqlite
    # only depend on redis (which is in this base file)
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - assistx_cache:/app/.cache
      - ./artifacts:/app/artifacts
      - transcriptions:/app/transcriptions
      - ./.assistx_cache.sqlite:/app/.assistx_cache.sqlite
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 15s

  worker:
    build:
      context: .
    container_name: assistx-worker
    command: python /app/worker.py
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - NEO4J_URI=${NEO4J_URI:-bolt://neo4j:7687}
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-livelongandprosper}
      - OLLAMA_HOST=${OLLAMA_HOST:-http://ollama:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-gemma:2b}
      - CACHE_PATH=/app/.assistx_cache.sqlite
      - WHISPER_DEVICE=${WHISPER_DEVICE:-auto}
      - WHISPER_COMPUTE_TYPE=${WHISPER_COMPUTE_TYPE:-int8}
      - TRANSCRIPTIONS_ROOT=/app/transcriptions
      - XDG_CACHE_HOME=/app/.cache
    depends_on:
      - redis
    volumes:
      - assistx_cache:/app/.cache
      - ./artifacts:/app/artifacts
      - transcriptions:/app/transcriptions
      - ./.assistx_cache.sqlite:/app/.assistx_cache.sqlite
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python - <<'PY'\nimport urllib.request,sys\ntry:\n  urllib.request.urlopen('http://localhost:8000/health', timeout=2)\n  print('ok')\n  sys.exit(0)\nexcept Exception as e:\n  print(e); sys.exit(1)\nPY"
        ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

volumes:
  assistx_cache: {}
  transcriptions: {}
