#!/usr/bin/env python3
"""Conservative CI-only acceptance report; never exercises a fleet node.

The collector reads pytest JUnit XML generated by an existing offline test step.
It cannot grant production authority, and never accepts external 'deployed pass'
assertions. Unknown, missing, failed, or skipped evidence fails closed.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from xml.etree import ElementTree

SCHEMA = "assistx.trace-acceptance.v1"
PROVENANCE = "unit_fixture"
SHA = re.compile(r"^[a-fA-F0-9]{40}$")
# Exact expected source test names, not substring matches over arbitrary output.
REQUIRED = {
    "lease_freshness": (
        "test_trace_claim_lease::test_readonly_claim_snapshot_yields_short_node_bound_proof",
        "test_trace_claim_lease::test_signature_type_target_ttl_and_time_validation",
        "test_trace_claim_lease::test_fresh_signed_status_requires_exact_challenge_and_current_claim",
    ),
    "revocation_supersession": (
        "test_trace_claim_lease::test_issuer_fails_closed_for_noncurrent_claims",
        "test_trace_claim_lease::test_fresh_signed_status_requires_exact_challenge_and_current_claim",
    ),
    "wrong_node_replay": (
        "test_trace_claim_lease::test_issuer_requires_exact_node_task_and_generation",
        "test_trace_claim_lease::test_signature_type_target_ttl_and_time_validation",
        "test_trace_shadow_grant::test_wrong_node_denied_without_journal",
        "test_trace_execution_adapter::test_noop_and_duplicate_claim_cannot_rerun",
    ),
    "production_api": (
        "test_trace_claim_lease::test_api_is_off_by_default_and_identity_checked_before_neo",
        "test_trace_claim_live_executor::test_worker_lifecycle_claim_two_proofs_and_completion",
    ),
    "key_custody": (
        "test_trace_claim_lease::test_signing_key_must_be_owner_only_and_no_symlinks",
        "test_trace_shadow_grant::test_per_node_key_bootstrap_is_idempotent_and_distinct",
    ),
    "audit_nas_custody": (
        "test_trace_execution_adapter::test_tampered_journal_is_denied",
        "test_trace_segment_nas::test_independent_verifier_refuses_witness_reset",
        "test_trace_segment_nas::test_publisher_rejects_insecure_destination_before_writing",
    ),
    "physical_negative_admission": (
        "test_trace_claim_live_executor::test_disabled_or_missing_prerequisite_denies_before_http",
        "test_trace_claim_live_executor::test_worker_does_not_claim_trace_if_local_preflight_fails",
        "test_trace_claim_live_executor::test_advertised_capability_requires_all_real_prerequisites",
    ),
    "ci_baseline": (),
}
BLOCKERS = {
    "lease_freshness": ["deployed_authenticated_issuer_absent", "monotonic_fencing_unproven"],
    "revocation_supersession": ["real_revocation_and_midflight_cancellation_unproven"],
    "wrong_node_replay": ["authenticated_two_node_physical_denial_unproven"],
    "production_api": ["deployed_route_startup_authentication_unproven"],
    "key_custody": ["receiver_owned_issuer_keys_escrow_and_rotation_unproven"],
    "audit_nas_custody": ["restricted_cifs_acl_real_fsync_restore_and_independent_worm_unproven"],
    "physical_negative_admission": ["physical_direct_negative_admission_unproven"],
    "ci_baseline": ["broad_ci_main_baseline_not_verified"],
}


def read_junit(path: Path) -> tuple[dict[str, list[str]], list[str]]:
    results: dict[str, list[str]] = {}
    errors: list[str] = []
    if not path.is_file():
        return results, ["junit_missing"]
    try:
        root = ElementTree.parse(path).getroot()
        if root.tag not in {"testsuites", "testsuite"}:
            raise ValueError("unexpected_junit_root")
        for case in root.iter("testcase"):
            classname = case.get("classname", "")
            name = case.get("name", "")
            module = classname.rsplit(".", 1)[-1]
            if not re.fullmatch(r"test_[A-Za-z0-9_]+", module):
                continue
            function = name.split("[", 1)[0]
            if not re.fullmatch(r"test_[A-Za-z0-9_]+", function):
                continue
            key = module + "::" + function
            state = "passed"
            if case.find("error") is not None:
                state = "error"
            elif case.find("failure") is not None:
                state = "failed"
            elif case.find("skipped") is not None:
                state = "skipped"
            results.setdefault(key, []).append(state)
        if not results:
            errors.append("junit_empty_or_unrecognized")
    except (ElementTree.ParseError, OSError, ValueError) as exc:
        errors.append("junit_invalid:" + type(exc).__name__)
    return results, errors


def create_report(
    junit: Path, *, head: str, base: str, tested: str,
    run_url: str = "", observed_at: str | None = None
) -> dict:
    observed_at = observed_at or datetime.now(timezone.utc).isoformat()
    tests, errors = read_junit(junit)
    if not SHA.fullmatch(head):
        errors.append("pr_head_sha_missing_or_invalid")
    if not SHA.fullmatch(base):
        errors.append("pr_base_sha_missing_or_invalid")
    if not SHA.fullmatch(tested):
        errors.append("tested_checkout_sha_missing_or_invalid")
    digest = hashlib.sha256(junit.read_bytes()).hexdigest() if junit.is_file() else None
    gates = {}
    for gate, required in REQUIRED.items():
        checks = []
        for test_id in required:
            cases = tests.get(test_id, [])
            passed = bool(cases) and all(state == "passed" for state in cases)
            checks.append({
                "test_id": test_id,
                "result": "pass" if passed else "blocked",
                "case_count": len(cases),
                "reason": None if passed else (
                    "missing_test" if not cases else "failed_skipped_or_errored"
                ),
                "provenance": PROVENANCE,
                "evidence_digest": digest,
            })
        fixtures_ok = bool(required) and all(c["result"] == "pass" for c in checks) and not errors
        gates[gate] = {
            "fixture_status": "fixture_pass" if fixtures_ok else "blocked",
            "activation_status": "blocked",
            "checks": checks,
            "activation_blockers": BLOCKERS[gate],
        }
    return {
        "schema": SCHEMA,
        "pull_request": 119,
        "repository": "scottjoyner/auto-assist",
        "observed_at": observed_at,
        "pr_head_sha": head if SHA.fullmatch(head) else None,
        "pr_base_sha": base if SHA.fullmatch(base) else None,
        "tested_checkout_sha": tested if SHA.fullmatch(tested) else None,
        "checkout_matches_pr_head": bool(SHA.fullmatch(head) and head.lower() == tested.lower()),
        "junit_sha256": digest,
        "evidence_provenance": PROVENANCE,
        "evidence_run_url": run_url or None,
        "collector_errors": errors,
        "gates": gates,
        "production_dispatch_authorized": False,
        "promotion_eligible": False,
    }


def validate_report(report: dict) -> None:
    if report.get("schema") != SCHEMA or report.get("promotion_eligible") is not False:
        raise ValueError("unsafe_report_schema_or_promotion")
    if report.get("production_dispatch_authorized") is not False:
        raise ValueError("unsafe_production_authority")
    if set(report.get("gates", {})) != set(REQUIRED):
        raise ValueError("missing_or_extra_gates")
    for gate_id, item in report["gates"].items():
        if item.get("activation_status") != "blocked" or not item.get("activation_blockers"):
            raise ValueError("unsafe_gate:" + gate_id)
        if len(item.get("checks", [])) != len(REQUIRED[gate_id]):
            raise ValueError("missing_checks:" + gate_id)
        for check in item["checks"]:
            if check.get("provenance") != PROVENANCE or check.get("result") not in {"pass", "blocked"}:
                raise ValueError("unsafe_evidence:" + gate_id)
    if report.get("collector_errors") and any(
        gate["fixture_status"] == "fixture_pass" for gate in report["gates"].values()
    ):
        raise ValueError("fixture_pass_with_collector_errors")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--junit", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--head", default="")
    parser.add_argument("--base", default="")
    parser.add_argument("--tested", default="")
    parser.add_argument("--run-url", default="")
    args = parser.parse_args()
    report = create_report(args.junit, head=args.head, base=args.base,
                           tested=args.tested, run_url=args.run_url)
    validate_report(report)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, sort_keys=True, indent=2) + "\n", encoding="utf-8")
    print("trace acceptance report:", args.output)
    print("fixture gates passed:", sum(g["fixture_status"] == "fixture_pass" for g in report["gates"].values()), "/", len(REQUIRED))
    print("production promotion: BLOCKED")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
